POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVicmFoaW05NSIsImlkIjoiNjM5Y2Q0YTgzYzkyMjcyZjQ1ZDNhM2QxIiwiaWF0IjoxNjcxNzY4MjM5LCJleHAiOjE2NzE3NzE4Mzl9.7KyPWmsQqkt5GQaG4xvN118eXAQdhrmI2EkexgpyKVg 

{
  "title": "run like me",
  "author": "Ebrahim Haji",
  "url": "yahoo.com",
  "likes": 3
}