POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVicmFoaW05NSIsImlkIjoiNjM5Y2Q0YTgzYzkyMjcyZjQ1ZDNhM2QxIiwiaWF0IjoxNjcxMjIzMDUwfQ.e_ClPF5XIsu-LYKa96pZAIpciZ5HJ13HIZlfJEWya0Q 

{
  "title": "run like the wind",
  "author": "Ebrahim Haji",
  "url": "google.com",
  "likes": 3,
  "userId": "639cd4a83c92272f45d3a3d1"
}